### ISSUE TITLE
麻烦加个 preview

### ISSUE THREAD

**Issue by 88250** [Achuan-2/siyuan-widget-clockpac#1]
![image](https://user-images.githubusercontent.com/873584/136825963-7846ec98-be34-4c39-93e6-7cfc3aab8a04.png)

**Comment by Achuan-2** [comment]
1bb3accb5d4f24723ab6f55265ee3cd172e27df5
啊，忘了，对不起

**Comment by 88250** [comment]
没事的，集市已经部署 🎉
